name: Publish to Docker Hub

on:
  push:
    branches:
      - dev
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: name1
      run: echo "${GITHUB_BASE_REF}"
    - name: name2
      run: echo $(echo $GITHUB_REF | cut -d'/' -f 3)
